# id = Column(Integer(), primary_key=True, autoincrement=True)
# cepod = Column(String(SHORT_TEXT_LENGTH), nullable=False)
# date_of_surgery = Column(Date, nullable=False)
# date_of_dc = Column(Date, nullable=False)
# los = Column(Integer, nullable=False)
# operation = Column(ForeignKey('Operations.id'), nullable=False)
# hospital = Column(ForeignKey('Hospitals.id'), nullable=False)
# side = Column(String(5), nullable=False)
# primary = Column(Boolean, nullable=False, default=True)
# type = Column(String(SHORT_TEXT_LENGTH), nullable=False)
# additional_procedure = Column(String(LONG_TEXT_LENGTH), nullable=False, default='none')
# antibiotics = Column(String(LONG_TEXT_LENGTH), nullable=False, default='none')
# interval = Column(Integer, nullable=False, default=0)
# opd_rv_date = Column(Date, nullable=False, default=date.today)
# opd_pain = Column(String(SHORT_TEXT_LENGTH), nullable=False, default='none')
# opd_numbness = Column(String(SHORT_TEXT_LENGTH), nullable=False, default='none')
# opd_infection = Column(String(SHORT_TEXT_LENGTH), nullable=False, default='none')
# opd_comments = Column(String(LONG_TEXT_LENGTH), nullable=False, default='none')
# comments = Column(String(LONG_TEXT_LENGTH), nullable=False, default='none')
